default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: <%= ENV["SECRET_MESSAGES_LOCAL_DATABASE_USERNAME"] %>
  password: <%= ENV["SECRET_MESSAGES_LOCAL_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: secret_messages_development
  host: localhost

test:
  <<: *default
  database: secret_messages_test
  host: localhost

production:
  <<: *default
  database: secret_messages_production
  username: secret_messages
  password: <%= ENV["SECRET_MESSAGES_DATABASE_PASSWORD"] %>
